version: '3'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./db-scripts/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./db-scripts/create-metabase-db.sh:/docker-entrypoint-initdb.d/create-metabase-db.sh
      - ./files:/files
    ports:
      - 5432:5432
    networks:
      - db

  metabase:
    container_name: metabase
    image: metabase/metabase
    depends_on:
      - db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: db
    ports:
      - 3000:3000
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
